swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      tags:
        - Transaction Module
      summary: Get Transactions for Current Month
      description: Retrieve all transactions for the current month, grouped by account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/transactions/{transactionId}:
     get:
      tags:
        - Transaction Module
      summary: Get Transactions for Current Month
      description: Retrieve all transactions for the current month, grouped by account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: "object"
    properties:
      accountId:
        type: "string"
        description: "ID du compte associé à la transaction"
      amount:
        type: "number"
        description: "Montant de la transaction"
      description:
        type: "string"
        description: "Description de la transaction"
      date:
        type: "string"
        format: "date-time"
        description: "Date et heure de la transaction"
  TransactionUpdate:
    type: object
    properties:
      amount:
        type: number
        description: Updated amount of the transaction
      description:
        type: string
        description: Updated description of the transaction
      date:
        type: string
        format: date-time
        description: Updated date and time of the transaction
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
