swagger: '2.0'
info:
  version: 1.0.0
  title: API de Transactions
paths:
  /transactions:
    get:
      summary: Récupérer toutes les transactions du mois en cours
      description: Retourne la liste des transactions groupées par compte pour le mois en cours.
      responses:
        200:
          description: Succès
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
  /transactions/{transactionId}:
    get:
      summary: Récupérer les détails d'une transaction
      description: Retourne les détails d'une transaction spécifique.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID de la transaction à récupérer
      responses:
        200:
          description: Succès
          schema:
            $ref: '#/definitions/Transaction'
    patch:
      summary: Mettre à jour une transaction
      description: Met à jour les informations d'une transaction spécifique.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID de la transaction à mettre à jour
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TransactionInput'
      responses:
        200:
          description: Succès
    delete:
      summary: Supprimer une transaction
      description: Supprime une transaction spécifique.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID de la transaction à supprimer
      responses:
        204:
          description: Succès sans contenu
definitions:
  Transaction:
    type: object
    properties:
      transactionId:
        type: string
      account:
        type: string
      amount:
        type: number
      date:
        type: string
  TransactionInput:
    type: object
    properties:
      account:
        type: string
      amount:
        type: number
      date:
        type: string
